### ISSUE TITLE
Use E6 classes?

### ISSUE THREAD

**Issue by bjnortier** [bjnortier/flow#3]
There's a lot of boilerplate at the moment for classes, I'm wondering if it's a good idea to start using ES6 classes and a transcoder like https://github.com/google/traceur-compiler.

As soon as ES6 classes are available in current browsers the switch will be made regardless.

**Comment by bjnortier** [comment]
What do you think @xoryouyou?

**Comment by xoryouyou** [comment]
:+1: 

Would definitely do this.  
Havent used Traceur but babel comes in very handy for this.

See https://babeljs.io/docs/setup/#webpack  for example.
